version: '3.8'
services:
  back:
    build: ./back
    ports:
      - "3001:3001"
    container_name: back
    networks:
      - app-network
  front:
    build: ./front
    ports:
      - "3000:3000"
    container_name: front
    depends_on:
      - back
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001 # Atualizado para localhost
    networks:
      - app-network
networks:
  app-network:
    driver: bridge